// Shopify 配置
export const SHOPIFY_CONFIG = {
  // 这些值应该从环境变量中获取
  SHOPIFY_STORE_DOMAIN: process.env.SHOPIFY_STORE_DOMAIN || '',
  SHOPIFY_STOREFRONT_ACCESS_TOKEN: process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN || '',
  SHOPIFY_ADMIN_ACCESS_TOKEN: process.env.SHOPIFY_ADMIN_ACCESS_TOKEN || '',
  SHOPIFY_WEBHOOK_SECRET: process.env.SHOPIFY_WEBHOOK_SECRET || '',
} as const;

// GraphQL 查询
import { GET_PRODUCTS, GET_PRODUCT_BY_HANDLE } from './queries/products';
import { GET_COLLECTIONS } from './queries/collections';
import { CART_CREATE, CART_GET, CART_LINES_ADD, CART_LINES_UPDATE, CART_LINES_REMOVE } from './queries/cart';
import { CUSTOMER_CREATE, CUSTOMER_ACCESS_TOKEN_CREATE, CUSTOMER_ACCESS_TOKEN_RENEW, CUSTOMER_BY_TOKEN, CUSTOMER_ACCESS_TOKEN_DELETE, CUSTOMER_ORDERS, CUSTOMER_UPDATE, CUSTOMER_RECOVER, CUSTOMER_RESET } from './queries/customers';

export const SHOPIFY_QUERIES = {
  GET_PRODUCTS,
  GET_PRODUCT_BY_HANDLE,
  GET_COLLECTIONS,
  CART_CREATE,
  CART_GET,
  CART_LINES_ADD,
  CART_LINES_UPDATE,
  CART_LINES_REMOVE,
  CUSTOMER_CREATE,
  CUSTOMER_ACCESS_TOKEN_CREATE,
  CUSTOMER_ACCESS_TOKEN_RENEW,
  CUSTOMER_BY_TOKEN,
  CUSTOMER_ACCESS_TOKEN_DELETE,
  CUSTOMER_ORDERS,
  CUSTOMER_UPDATE,
  CUSTOMER_RECOVER,
  CUSTOMER_RESET,
} as const;